services:
  sftpslurper:
    container_name: "sftpslurper"
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    user: "1000:1000"
    ports:
      - 8080:8080
      - 2222:2222
    volumes:
      - ./cmd/sftpslurper/uploads:/dist/uploads

